substitutions:
  devicename: "nous-a1t-fa2f07" # change this to the device name and comment out name_add_mac_suffix 
  friendly_name: "Nous A1T"
  current_resistor: "0.001" # Higher value gives lower watt readout
  voltage_divider: "2041" # Lower value gives lower voltage readout
  power_metering_update_interval: "3s"
  current_calibration: "0.8653846"
  voltage_calibration: "0.7783417"
  power_calibration: "0.7525866"

# logger:

packages:
  device_base: !include common/device_min.yaml
  device_nous_a1t: !include common/device_nous_a1t.yaml
