substitutions:
  devicename: "vindriktning-4c30b8" # change this to the device name and comment out name_add_mac_suffix 
  friendly_name: "Vindriktning"
  temperature_offset: "6.5"
  co2_forced_calibration_value: "418"  # outside average Dec 2022 (source: https://gml.noaa.gov/webdata/ccgg/trends/co2/co2_mm_gl.txt)

packages:
  device_base: !include common/device_base.yaml
  device_sonoff_mini: !include common/device_vindriktning.yaml

# dashboard_import:
#   package_import_url: github://tr4nt0r/homeassistant/vindriktning.yaml@main
#   import_full_config: true
