esphome:
  name: ${devicename}
  friendly_name: ${friendly_name}

  on_boot:
    priority: -100.0
    then:
      - wait_until:
          time.has_time:
      - sensor.template.publish:
          id: uptime_sensor
          state: !lambda return id(homeassistant_time).now().timestamp;

# Enable logging
# logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key
ota:
  password: !secret ota_password
  #id: my_ota

wifi:
  networks:
    # Default Network
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
    # Backup Network, connects to Home Assistant directly, no internet  
    - ssid: !secret backup_wifi_ssid
      password: !secret backup_wifi_password
    # connect to Mobile Hotspot of my Android Phone
    - ssid: "tr4nt0r"
      password: !secret ap_password

time:
  - platform: homeassistant
    id: homeassistant_time

    # Sensors with general information.
sensor:
  - platform: template
    name: "Uptime"
    id: uptime_sensor
    device_class: timestamp
    icon: mdi:clock
    entity_category: diagnostic
    update_interval: never

  - platform: wifi_signal
    name: "RSSI"
    id: rssi
    update_interval: 60s
    disabled_by_default: true

# Text sensors with general information.
text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP"
      icon: mdi:ip-network
      update_interval: 600s
    mac_address:
      name: "MAC"
      icon: mdi:network
    ssid:
      name: "SSID"
      icon: mdi:wifi
    bssid:
      name: "BSSID"
      icon: mdi:wifi
    dns_address:
      name: "DNS"
      icon: mdi:dns

button:
  - platform: template
    name: "Identify"
    id: identify
    entity_category: diagnostic
    on_press:
      - repeat:
          count: 20
          then:
            - light.turn_on: default_status_led
            - delay: 500ms
            - light.turn_off: default_status_led
            - delay: 500ms

  - platform: restart
    id: restart_device
    name: "Restart"

  - platform: safe_mode
    name: "Restart (Safe Mode)"

  - platform: factory_reset
    id: reset
    name: "Factory Reset"
    entity_category: diagnostic
    disabled_by_default: true

binary_sensor:
  - platform: status
    name: "Status"
