
esphome:
    comment: "SONOFF SV Safe Voltage WiFi Wireless Switch"
    project:
      name: "Sonoff.SV"
      version: "1.0.0"

esp8266:
    board: sonoff_sv

output:
  - platform: esp8266_pwm
    id: green_led
    pin:
      number: GPIO13
      inverted: true

light:
  - platform: monochromatic
    id: led
    name: "Status LED"
    output: green_led
    entity_category: config 
    restore_mode: RESTORE_DEFAULT_OFF
    
  - platform: status_led
    id: default_status_led
    output: green_led


    
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    id: onoff_button
    filters:
      - delayed_on_off: 10ms
    on_press:
      - switch.toggle: relay
    on_double_click :
      button.press: restart_device
    on_click:
      min_length: 10s
      max_length: 20s
      then:
        - button.press: reset



  # - platform: gpio
  #   pin: GPIO1   # RX pin (for external sensors)
  #   id: sensor_rx
  #   name: "GPIO01/RX"
  #   disabled_by_default: true

  # - platform: gpio
  #   pin: GPIO2   # E-LOG pin (From PCB V2.1; for external sensors)
  #   id: sensor_elog
  #   name: "GPIO2/E-LOG"
  #   disabled_by_default: true

  # - platform: gpio
  #   pin: GPIO3   # TX pin (for external sensors)
  #   id: sensor_tx
  #   name: "GPIO03/TX"
  #   disabled_by_default: true


switch:
  - platform: gpio
    name: "Switch"
    device_class: switch
    pin: GPIO12
    id: relay
    restore_mode: RESTORE_DEFAULT_OFF 

  - platform: template
    name: "Decoupled Mode"
    id: decoupled_mode
    restore_mode: RESTORE_DEFAULT_OFF
    optimistic: true
    entity_category: config
    icon: "mdi:connection"
