# minimal firmware for esp8266 for OTA updates 
esphome:
  name: ${devicename}
  friendly_name: ${friendly_name}

esp8266:
  board: esp01_1m

# Enable logging
# logger:

# Enable Home Assistant API
# api:
#   encryption:
#     key: !secret api_encryption_key
ota:
  password: !secret ota_password
  #id: my_ota

wifi:
  networks:
    # Default Network
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
    # Backup Network, connects to Home Assistant directly, no internet  
    - ssid: !secret backup_wifi_ssid
      password: !secret backup_wifi_password
    # connect to Mobile Hotspot of my Android Phone
    - ssid: "tr4nt0r"
      password: !secret ap_password

web_server:
  port: 80
  version: 2
  ota: true
  include_internal: false
  